project:
  type: website
  output-dir: _site
  preview:
    port: 5555
    browser: false
    watch-inputs: true
    navigate: true
  # render:
  #   - "*.qmd"
  #   - "about/*.qmd"
  #   - "case-studies/**/*.qmd"
  #   - "projects/**/*.qmd"
  #   - "blog/**/*.qmd"
  #   - "resume/*.qmd"

profile: 
  default: development

execute: 
  # Development: always re-execute changed content while iterating.
  freeze: auto

website:
  title: "Tyler Pollard (DEV)"
  description: "Portfolio website of Tyler Pollard, Statistician"
  favicon: "logos/tyler-pollard-icon.png"
  site-url: "https://tylerpollard410.github.io/"
  repo-url: "https://github.com/TylerPollard410/TylerPollard410.github.io"

  google-analytics: "G-LG5XRX930Y"

  twitter-card: 
    image: "/files/profiles/twitter-card-large.png"
    card-style: summary_large_image
    creator: "@tylerpollard410"
    site: "@tylerpollard410"

  navbar:
    # background: primary
    # Hide text title and use the brand logo (logo.small) instead.
    title: Tyler Pollard
    logo: small
    left:
      - href: index.qmd
        text: Home
      - href: about/index.qmd
        text: About
      - href: projects/index.qmd
        text: Projects
      - href: case-studies/index.qmd
        text: Case Studies
      - href: blog/index.qmd
        text: Blog
      - href: resume/index.qmd
        text: CV
    right: 
      - icon: github
        href: https://github.com/TylerPollard410
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/tyler-pollard-763b8315b/
        target: _blank
      - icon: envelope
        href: "mailto:tylerpollard410@gmail.com"
        target: _blank
    search: false
  page-footer: 
    left: |
      &copy; 2024 &mdash; 2026 Tyler Pollard.<br>
      All rights reserved.
    right: |
      Website built with [![](/logos/quarto.png){height=1em}](https://quarto.org)
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true

preview-colour:
  code: true

brand:
  dark: _extensions/TylerPollard410/my-brand/brand-dark.yml
  light: _extensions/TylerPollard410/my-brand/brand-light.yml

format:
  # Quarto format placeholders (keep allowed formats only)
  html:
    axe: true
    theme:
      dark:
        - default
        - brand
        #- my-brand
        - _extensions/TylerPollard410/my-brand/styles.scss
      light:
        - default
        - brand
        #- my-brand
        - _extensions/TylerPollard410/my-brand/styles.scss
    # css: styles.scss
    respect-user-color-scheme: false
    toc: true
    anchor-sections: true
